[package]
name = "framebuffer"
version = "0.1.0"
authors = ["Wenqiu Yu <yuwenqiuj@gmail.com>"]
description = "a framebuffer is a buffer of pixels which can be composited to another framebuffer or be mapped to some physical memory"
build = "../../build.rs"
edition = "2018"

[dependencies]
owning_ref = { git = "https://github.com/kevinaboos/owning-ref-rs" }
zerocopy = "0.3.0"

[dependencies.memory]
path = "../memory"

[dependencies.multicore_bringup]
path = "../multicore_bringup"

[dependencies.shapes]
path = "../shapes"

[dependencies.color]
path = "../color"

[lib]
crate-type = ["rlib"]
