[package]
name = "sdt"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "Support for ACPI SDT and other descriptor tables"
build = "../../build.rs"
edition = "2018"

[dependencies]
zerocopy = "0.3.0"

