[package]
name = "rsdp"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "Support for ACPI RSDP"
build = "../../build.rs"
edition = "2018"

[dependencies]
owning_ref = { git = "https://github.com/kevinaboos/owning-ref-rs" }
zerocopy = "0.3.0"

[dependencies.memory]
path = "../memory"
