[package]
name = "rsdp"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "Support for ACPI RSDP"
build = "../../build.rs"

[dependencies]
zerocopy = "0.3.0"

[dependencies.owning_ref]
path = "../../libs/owning_ref"

[dependencies.memory]
path = "../memory"
