[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "vga_buffer"
description = "Support for the simple 80x25 text-only VGA display mode"
version = "0.1.0"
build = "../../build.rs"
edition = "2018"

[dependencies]
spin = "0.4.10"

[dependencies.volatile]
version = "0.2.7"
features = ["const_fn"]

[dependencies.serial_port]
path = "../serial_port"

[dependencies.kernel_config]
path = "../kernel_config"

[lib]
crate-type = ["rlib"]
