[package]
name = "acpi_table"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "Definitions for ACPI tables bookkeeping"
build = "../../build.rs"
edition = "2018"

[dependencies]
zerocopy = "0.3.0"

[dependencies.log]
version = "0.4.8"

[dependencies.memory]
path = "../memory"

[dependencies.sdt]
path = "../sdt"
