[package]
name = "fadt"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "Support for ACPI FADT"
build = "../../build.rs"
edition = "2018"

[dependencies]
zerocopy = "0.3.0"

[dependencies.memory]
path = "../memory"

[dependencies.sdt]
path = "../sdt"

[dependencies.acpi_table]
path = "../acpi_table"

